// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBYjtxZBw1dXrHKKPUdJhxTU7LpCPqnFj4',
    appId: '1:246446465737:web:efccc7a8443c9e769fa318',
    messagingSenderId: '246446465737',
    projectId: 'engineering-hub-7e5e1',
    authDomain: 'engineering-hub-7e5e1.firebaseapp.com',
    storageBucket: 'engineering-hub-7e5e1.firebasestorage.app',
    measurementId: 'G-3BL4N0HRDV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDblNUnMo0QrquQCs4reR4BYWCJoUgjp2Q',
    appId: '1:246446465737:android:76fe08fbba1453639fa318',
    messagingSenderId: '246446465737',
    projectId: 'engineering-hub-7e5e1',
    storageBucket: 'engineering-hub-7e5e1.firebasestorage.app',
  );
}
